version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
    - "3AP-AG/3ap-admin"


  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
    - "3AP-AG/3ap-admin"