openapi: 3.0.1
info:
  title: Harvest Forecast 
  description: 'API Overview for Harvest Forecast'
  contact:
    email: cyril@3ap.ch
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
externalDocs:
  description: Harvest Forecast
  url: https://www.getharvest.com/forecast
servers:
- url: https://api.forecastapp.com
tags:
- name: whoamI
  description: Who am I
- name: people
  description: Get details of peoplep
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
paths:
  /whoami:
    get:
      tags:
      - whoamI
      summary: Get Info about the logged in User
      operationId: getWhoAmI
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentUser'
      security: 
      - forecast_auth: []
      - forecast_account_id: []
  /people:
    get:
      tags:
      - people
      summary: Get details of all persons
      operationId: getPeople
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/People'
      security: 
      - forecast_auth: []
      - forecast_account_id: []    
  /people/{id}:
    get:
      tags:
      - people
      summary: GetGet specific person by id
      operationId: getPersonById
      parameters:
      - name: id
        in: path
        description: 'The id of the user'
        required: true
        schema:
          type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        404:
          description: Person not found
          content: {}   
      security: 
      - forecast_auth: []
      - forecast_account_id: []        
components:
  schemas:
    CurrentUser:
      type: object
      properties:
        id:
          type: integer
          format: int64
        account_ids:
          type: array
          items:
            type: integer
    People:
      type: object
      properties:
        people:
          type: array
          items:
            $ref: '#/components/schemas/Person'
    Person:
      type: object
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
            type: string
        email:
            type: string
        login:
            type: string
            description: Login Status
            enum:
            - enabled
            - disabled
        admin:
            type: boolean
        archived:
            type: boolean
        subscribed:
            type: boolean
        avatar_url:
            type: string
        roles:
            type: array
            items:
                type: string
        updated_at: 
            type: string
            format: date-time
        updated_by_id:
            type: integer
            format: int64
        harvest_user_id:
            type: integer
            format: int64
        weekly_capacity:
            type: integer
            format: int64
        working_days:
          type: object
          additionalProperties:
            type: boolean
        color_blind: 
            type: boolean
        personal_feed_token_id:
            type: integer
            format: int64   
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  securitySchemes:
    forecast_auth:
      type: http
      scheme: bearer
    forecast_account_id:
      type: apiKey
      name: forecast-account-id
      in: header
