openapi: 3.0.1

info:
  title: Harvest Forecast API
  version: v0.1.0
  contact:
    name: Harvest API Support
    email: support@harvestapp.com
    url: https://www.getharvest.com/contact

externalDocs:
  description: "Forecast docs: getharvest.com/forecast"
  url: https://www.getharvest.com/forecast

servers:
  - url: https://api.forecastapp.com

security:
  - bearerAuth: [] # apply bearer auth to all endpoints

tags:
  - name: assignments
    description: |
      Create, Update, and Delete an Assignment, and List all Assignments
  - name: clients
    description: Read a Client, and list all Clients
  - name: milestones
    description: List all Milestones
  - name: people
    description: Read a Person, and list all People
  - name: placeholders
    description: List all Placeholders
  - name: projects
    description: Read a Project, list all Projects, and push to Harvest
  - name: roles
    description: List all Roles
  - name: whoami
    description: Get info about the currently authenticated user

paths:
  # whoami
  /whoami:
    $ref: "./paths/whoami.yaml"

  # people
  /people:
    $ref: "./paths/people.yaml#/people"
  /people/{personId}:
    $ref: "./paths/people.yaml#/person-by-id"

  # projects
  /projects:
    $ref: "./paths/projects.yaml#/projects"
  /projects/{projectId}:
    $ref: "./paths/projects.yaml#/project-by-id"

  # clients
  /clients:
    $ref: "./paths/clients.yaml#/clients"
  /clients/{clientId}:
    $ref: "./paths/clients.yaml#/client-by-id"

  # roles
  /roles:
    $ref: "./paths/roles.yaml"

  # placeholders
  /placeholders:
    $ref: "./paths/placeholders.yaml"

  # assignments
  /assignments:
    $ref: "./paths/assignments.yaml#/assignments"
  /assignments/{assignmentId}:
    $ref: "./paths/assignments.yaml#/assignment-by-id"

  # milestones
  /milestones:
    $ref: "./paths/milestones.yaml"


components:
  securitySchemes:
    bearerAuth:
      description: |
        This API uses OAuth2, with the Authorization Code flow, to authenticate.
        See the docs at https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/
      type: http
      scheme: bearer
      bearerFormat: JWT
